# Generated by Django 4.1.2 on 2022-10-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('mfc_1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mfc_2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mfc_3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mfc_4', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
